openapi: 3.0.3
info:
  title: WhipSeeker API
  version: 1.0.0
  description: >
    This is the OpenAPI specification for the WhipSeeker platform, covering consumer and dealer APIs.

servers:
  - url: https://api.whipseeker.com/v1

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: []

paths:
  /listings:
    get:
      summary: Get all listings
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK 